from matplotlib import cm
from matplotlib.colors import ListedColormap, LinearSegmentedColormap
from enum import IntEnum
import numpy as np
import streamlit as st

# 2026 season
season_start_month = 3
season_start_day = 28
preseason_start_month = 3
preseason_start_day = 12
futures_season_start_month = 3
futures_season_start_day = 20

woba_values = {
    # BB, HBP, 1B, 2B, 3B, HR
    # 2025.10.10 update
    2016: [0.759, 0.792, 0.924, 1.293, 1.742, 1.943],
    2017: [0.751, 0.775, 0.912, 1.300, 1.553, 1.905],
    2018: [0.747, 0.757, 0.899, 1.260, 1.579, 1.936],
    2019: [0.768, 0.787, 0.934, 1.303, 1.766, 2.069],
    2020: [0.767, 0.773, 0.923, 1.336, 1.548, 1.969],
    2021: [0.775, 0.797, 0.937, 1.363, 1.603, 2.076],
    2022: [0.782, 0.811, 0.921, 1.318, 1.778, 2.080],
    2023: [0.767, 0.797, 0.940, 1.377, 1.773, 2.043],
    2024: [0.776, 0.799, 0.923, 1.297, 1.508, 1.925],
    2025: [0.774, 0.783, 0.935, 1.293, 1.662, 2.050],
}


class SACode(IntEnum):
    Barrel = 0
    SolidContact = 1
    FlareBurner = 2
    PoorlyUnder = 3
    PoorlyTopped = 4
    PoorlyWeak = 5
    Unclassified = 6


class EVLABBClass(IntEnum):
    BR = 0
    LD = 1
    FB = 2
    GB = 3
    PU = 4
    UC = 5

teamNamesKortoEng = {
    '전체': {
        '한화': ('HAN_EAG', 'MIN_HAN'),
        'LG': ('LG_TWI', 'MIN_LGT'),
        'KT': ('KT_WIZ', 'MIN_KTW'),
        'NC': ('NC_DIN', 'MIN_NCD'),
        'SSG': ('SSG_LAN', 'MIN_SSG', 'SK_WYV', 'MIN_SKW'),
        'KIA': ('KIA_TIG', 'MIN_KIA'),
        '롯데': ('LOT_GIA', 'MIN_LOT'),
        '두산': ('DOO_BEA', 'MIN_DOO'),
        '삼성': ('SAM_LIO', 'MIN_SAM'),
        '키움': ('KIW_HER', 'MIN_HER', 'NEX_HER'),
        '상무': ('KBO_ARM'),
        '소뱅': ('MIN_HAW'),
    },
    '1군': {
        '한화': ('HAN_EAG'),
        'LG': ('LG_TWI'),
        'KT': ('KT_WIZ'),
        'NC': ('NC_DIN'),
        'SSG': ('SSG_LAN', 'SK_WYV'),
        'KIA': ('KIA_TIG'),
        '롯데': ('LOT_GIA'),
        '두산': ('DOO_BEA'),
        '삼성': ('SAM_LIO'),
        '키움': ('KIW_HER', 'NEX_HER'),
    },
    '퓨처스': {
        '한화': ('MIN_HAN'),
        'LG': ('MIN_LGT'),
        'KT': ('MIN_KTW'),
        'NC': ('MIN_NCD'),
        'SSG': ('MIN_SSG', 'MIN_SKW'),
        'KIA': ('MIN_KIA'),
        '롯데': ('MIN_LOT'),
        '두산': ('MIN_DOO'),
        '삼성': ('MIN_SAM'),
        '키움': ('MIN_HER'),
        '상무': ('KBO_ARM'),
        '소뱅': ('MIN_HAW'),
    },
}

팀이름트랙맨_한글코드변환 = {
    'MIN_DOO': 'OB',
    'MIN_HAN': 'HH',
    'MIN_HER': 'WO',
    'MIN_KIA': 'HT',
    'MIN_KTW': 'KT',
    'MIN_LGT': 'LG',
    'MIN_LOT': 'LT',
    'MIN_NCD': 'NC',
    'MIN_SAM': 'SS',
    'MIN_SSG': 'SK',
    'KBO_ARM': 'SM',
    'NEX_HER': 'WO',
    'SK_WYV': 'SK',
    'SAM_LIO': 'SS',
    'HAN_EAG': 'HH',
    'LG_TWI': 'LG',
    'NC_DIN': 'NC',
    'KT_WIZ': 'KT',
    'LOT_GIA': 'LT',
    'DOO_BEA': 'OB',
    'KIA_TIG': 'HT',
    'SSG_LAN': 'SK',
    'KIW_HER': 'WO',
}

teamCodeDict = {
    'HH': '한화',
    'LG': 'LG',
    'KT': 'KT',
    'NC': 'NC',
    'SK': 'SSG',
    'HT': 'KIA',
    'LT': '롯데',
    'OB': '두산',
    'SS': '삼성',
    'WO': '키움',
    'SM': '상무',
    'SOFTBANK': '소뱅'
}

팀한글명_영문코드로변환 = {
    '한화': 'HH',
    'LG': 'LG',
    'KT': 'KT',
    'NC': 'NC',
    'SSG': 'SK',
    'KIA': 'HT',
    '롯데': 'LT',
    '두산': 'OB',
    '삼성': 'SS',
    '키움': 'WO',
    '상무': 'SM',
    '소뱅': 'SOFTBANK',
}

tm_cols = [
    'PitchNo',
    'Date',
    'PAofInning',
    'PitchofPA',
    'Pitcher',
    'PitcherId',
    'PitcherThrows',
    'PitcherTeam',
    'Batter',
    'BatterId',
    'BatterSide',
    'BatterTeam',
    'Inning',
    'Top/Bottom',
    'Outs',
    'Balls',
    'Strikes',
    'TaggedPitchType',
    'PitchCall',
    'KorBB',
    'TaggedHitType',
    'PlayResult',
    'OutsOnPlay',
    'RunsScored',
    'RelSpeed',
    'VertRelAngle',
    'HorzRelAngle',
    'SpinRate',
    'SpinAxis',
    'RelHeight',
    'RelSide',
    'Extension',
    'VertBreak',
    'InducedVertBreak',
    'HorzBreak',
    'PlateLocHeight',
    'PlateLocSide',
    'VertApprAngle',
    'HorzApprAngle',
    'ExitSpeed',
    'Angle',
    'Distance',
    'Bearing',
    'HangTime',
    'HomeTeam',
    'AwayTeam',
    'Stadium',
    'Level',
    'League',
    'GameID',
    'ContactPositionX',
    'ContactPositionY',
    'ContactPositionZ',
    'RelSpeedGameDay',
    'PitchTypeGameDay',
    'PitchResultGameDay',
    'PAResultGameDay',
    'PAResultDetailGameDay',
    'Description',
    'ScoreHome',
    'ScoreAway',
    'On1BId',
    'On2BId',
    'On3BId',
    'Pos1Id',
    'Pos2Id',
    'Pos3Id',
    'Pos4Id',
    'Pos5Id',
    'Pos6Id',
    'Pos7Id',
    'Pos8Id',
    'Pos9Id',
    'PlateLocSideGameDay',
    'PlateLocHeightGameDay',
    'InducedVertBreakGameDay',
    'HorzBreakGameDay',
    'VertBreakGameDay',
    'RefereeGameDay',
    'SzBotGameDay',
    'SzTopGameDay',
    'xba',
    'xslg',
    'xwoba',
    'year',
    'game_date',
    'TotalPitches',
    'id',
]

tm_col_dtypes = {
    'PitchNo': 'Int32',
    'Date': str,
    'PAofInning': 'Int32',
    'PitchofPA': 'Int32',
    'Pitcher': str,
    'PitcherId': 'Int32',
    'PitcherThrows': str,
    'PitcherTeam': str,
    'Batter': str,
    'BatterId': 'Int32',
    'BatterSide': str,
    'BatterTeam': str,
    'Inning': 'Int32',
    'Top/Bottom': str,
    'Outs': 'Int32',
    'Balls': 'Int32',
    'Strikes': 'Int32',
    'TaggedPitchType': str,
    'PitchCall': str,
    'KorBB': str,
    'TaggedHitType': str,
    'PlayResult': str,
    'OutsOnPlay': 'Int32',
    'RunsScored': 'Int32',
    'RelSpeed': float,
    'VertRelAngle': float,
    'HorzRelAngle': float,
    'SpinRate': float,
    'SpinAxis': float,
    'RelHeight': float,
    'RelSide': float,
    'Extension': float,
    'VertBreak': float,
    'InducedVertBreak': float,
    'HorzBreak': float,
    'PlateLocHeight': float,
    'PlateLocSide': float,
    'VertApprAngle': float,
    'HorzApprAngle': float,
    'ExitSpeed': float,
    'Angle': float,
    'Distance': float,
    'Bearing': float,
    'HangTime': float,
    'HomeTeam': str,
    'AwayTeam': str,
    'Stadium': str,
    'Level': str,
    'GameID': str,
    'ContactPositionX': float,
    'ContactPositionY': float,
    'ContactPositionZ': float,
    'RelSpeedGameDay': 'Int32',
    'PitchTypeGameDay': str,
    'PitchResultGameDay': str,
    'PAResultGameDay': str,
    'PAResultDetailGameDay': str,
    'Description': str,
    'ScoreHome': 'Int32',
    'ScoreAway': 'Int32',
    'On1BId': 'Int32',
    'On2BId': 'Int32',
    'On3BId': 'Int32',
    'Pos1Id': 'Int32',
    'Pos2Id': 'Int32',
    'Pos3Id': 'Int32',
    'Pos4Id': 'Int32',
    'Pos5Id': 'Int32',
    'Pos6Id': 'Int32',
    'Pos7Id': 'Int32',
    'Pos8Id': 'Int32',
    'Pos9Id': 'Int32',
    'PlateLocSideGameDay': float,
    'PlateLocHeightGameDay': float,
    'InducedVertBreakGameDay': float,
    'HorzBreakGameDay': float,
    'VertBreakGameDay': float,
    'RefereeGameDay': str,
    'SzBotGameDay': float,
    'SzTopGameDay': float,
    'xba': float,
    'xslg': float,
    'xwoba': float,
    'year': 'Int32',
    'game_date': str,
    'TotalPitches': 'Int32',
    'id': 'Int32',
}


m_tm_cols = [
    'PitchNo',
    'PAofInning',
    'PitchofPA',
    'Pitcher',
    'PitcherId',
    'PitcherThrows',
    'PitcherTeam',
    'Batter',
    'BatterId',
    'BatterSide',
    'BatterTeam',
    'Inning',
    'Top/Bottom',
    'Outs',
    'Balls',
    'Strikes',
    'TaggedPitchType',
    'PitchCall',
    'KorBB',
    'TaggedHitType',
    'PlayResult',
    'OutsOnPlay',
    'RunsScored',
    'RelSpeed',
    'ExitSpeed',
    'Angle',
    'HomeTeam',
    'AwayTeam',
    'Stadium',
    'Level',
    'year',
    'game_date',
    'id',
    'month',
    'PA',
    'AB',
    'swing',
    'contact',
    'whiff',
    'hit',
    'xh',
    'single',
    'double',
    'triple',
    'homerun',
    'TB','walk',
    'hbp','sf','sh','gidp','strikeout','hardhit',
    'bip','bip_EV','bip_EVLA','bip_Dir','in_zone',
    'strike','wBB','wHBP','w1B','w2B','w3B','wHR',
    'out_numbers','woba_value','SpeedAngle_Code',
    'EVLA_BB_CLASS','woba','barrel','flareburner','poorlyUnder','poorlyTopped',
    'GB','FB','LD','PU',
    'BB_pull','BB_center','BB_oppo','BB_left','BB_right', 'PullAir',
    'xwoba_value','xba_value','xobp_value','xslg_value',
    'csw'
]

m_tm_col_dtypes = {
    'PitchNo': 'Int32',
    'PAofInning': 'Int32',
    'PitchofPA': 'Int32',
    'Pitcher': str,
    'PitcherId': 'Int32',
    'PitcherThrows': str,
    'PitcherTeam': str,
    'Batter': str,
    'BatterId': 'Int32',
    'BatterSide': str,
    'BatterTeam': str,
    'Inning': 'Int32',
    'Top/Bottom': str,
    'Outs': 'Int32',
    'Balls': 'Int32',
    'Strikes': 'Int32',
    'TaggedPitchType': str,
    'PitchCall': str,
    'KorBB': str,
    'TaggedHitType': str,
    'PlayResult': str,
    'OutsOnPlay': 'Int32',
    'RunsScored': 'Int32',
    'RelSpeed': float,
    'ExitSpeed': float,
    'Angle': float,
    'HomeTeam': str,
    'AwayTeam': str,
    'Stadium': str,
    'Level': str,
    'year': 'Int32',
    'game_date': str,
    'id': 'Int32',
    'month': 'Int32',
    'PA': 'Int32',
    'AB': 'Int32',
    'swing': 'Int32',
    'contact': 'Int32',
    'whiff': 'Int32',
    'hit': 'Int32',
    'xh': 'Int32',
    'single': 'Int32',
    'double': 'Int32',
    'triple': 'Int32',
    'homerun': 'Int32',
    'TB': 'Int32',
    'walk': 'Int32',
    'hbp': 'Int32',
    'sf': 'Int32',
    'sh': 'Int32',
    'csw': 'Int32',
    'gidp': 'Int32',
    'strikeout': 'Int32',
    'hardhit': 'Int32',
    'bip': 'Int32',
    'bip_EV': 'Int32',
    'bip_EVLA': 'Int32',
    'bip_Dir': 'Int32',
    'in_zone': 'Int32',
    'strike': 'Int32',
    'wBB': float,
    'wHBP': float,
    'w1B': float,
    'w2B': float,
    'w3B': float,
    'wHR': float,
    'out_numbers': 'Int32',
    'woba_value': float,
    'SpeedAngle_Code': 'Int32',
    'EVLA_BB_CLASS': 'Int32',
    'woba': float,
    'barrel': 'Int32',
    'flareburner': 'Int32',
    'GB': 'Int32',
    'FB': 'Int32',
    'LD': 'Int32',
    'PU': 'Int32',
    'BB_pull': 'Int32',
    'BB_center': 'Int32',
    'BB_oppo': 'Int32',
    'BB_left': 'Int32',
    'BB_right': 'Int32',
    'xwoba_value': float,
    'xba_value': float,
    'xobp_value': float,
    'xslg_value': float,
    'PullAir': 'Int32',
}

dmap_cols = [
    'game_date',
    'year',
    'Level',
    'GameID',
    'BatterId',
    'Batter',
    'BatterTeam',
    'BatterSide',
    'PitcherId',
    'PitcherThrows',
    'PlateLocSide',
    'PlateLocHeight',
    'PlateLocSideGameDay',
    'PlateLocHeightGameDay',
    'RelSpeed',
    'RelSpeedGameDay',
    'SzBotGameDay',
    'SzTopGameDay',
    'TaggedPitchType',
    'PitchCall',
    'PlayResult',
    'PitchResultGameDay',
    'PAResultGameDay',
    'KorBB',
    'OutsOnPlay',
    'TaggedHitType',
    'ExitSpeed',
    'Angle',
    'Bearing',
    'Distance',
    'HangTime',
    'Strikes', 'Balls', 'Outs',
    'xba', 'xslg', 'xwoba',
]

dmap_dtypes = {
    'game_date': str,
    'year': 'Int32',
    'Level': str,
    'GameID': str,
    'BatterId': 'Int32',
    'Batter': str,
    'BatterTeam': str,
    'BatterSide': str,
    'PitcherId': 'Int32',
    'PitcherThrows': str,
    'PlateLocSide': float,
    'PlateLocHeight': float,
    'PlateLocSideGameDay': float,
    'PlateLocHeightGameDay': float,
    'RelSpeed': float,
    'RelSpeedGameDay': float,
    'SzBotGameDay': float,
    'SzTopGameDay': float,
    'TaggedPitchType': str,
    'PitchCall': str,
    'PlayResult': str,
    'PitchResultGameDay': str,
    'PAResultGameDay': str,
    'KorBB': str,
    'OutsOnPlay': 'Int32',
    'TaggedHitType': str,
    'ExitSpeed': float,
    'Angle': float,
    'Bearing': float,
    'Distance': float,
    'HangTime': float,
    'Strikes': 'Int32', 'Balls': 'Int32', 'Outs': 'Int32',
    'xba': float, 'xslg': float, 'xwoba': float,
}

pitStatKeys = {
    'IP': '이닝',
    'PA': '타석',
    'hit': '피안타',
    'strikeout': '탈삼진',
    'walk': '볼넷',
    'homerun': '홈런',
    'BA': '피안타율',
    'OBP': '피출루율',
    'SLG': '피장타율',
    'OPS': '피OPS',
    'xBA': '기대피안타율',
    'xOBP': '기대피출루율',
    'xSLG': '기대피장타율',
    'xOPS': '기대피OPS',
    'Zone%': '존%',
    'Strike%': '스트%',
    'GB%': '땅볼%',
    'LD%': '라인%',
    'FB%': '뜬공%',
    'PU%': '팝업%',
    'GB/FB': '땅/뜬',
    'Hard%': '강한타구%',
    'Barrel%': '배럴%',
    'FlareBurner%': '안타성타구%',
    'Whiff%': '헛스윙%',
    'zCon%': '존컨택%',
    'Chase%': '체이스%',
    'Pitches': '투구수',
}

hitStatKeys = {
    'PA': '타석',
    'AB': '타수',
    'hit': '안타',
    'double': '2루타',
    'triple': '3루타',
    'homerun': '홈런',
    'BA': '타율',
    'OBP': '출루율',
    'SLG': '장타율',
    'OPS': 'OPS',
    'xBA': '기대타율',
    'xOBP': '기대출루율',
    'xSLG': '기대장타율',
    'xOPS': '기대OPS',
    'xwOBA': '기대wOBA',
    'Hard%': '강한타구%',
    'Barrel%': '배럴%',
    'FlareBurner%': '안타성타구%',
    'zSwing%': '존스윙%',
    'zCon%': '존컨택%',
    'Chase%': '체이스%',
    'GB%': '땅볼%',
    'LD%': '라인%',
    'FB%': '뜬공%',
    'PU%': '팝업%',
    'Pull%': '당긴%',
    'Center%': '가운데%',
    'Oppo%': '밀어친%',
    'MaxEV': '최대 타구속도',
    'MeanEV': '평균 타구속도',
    'MeanLA': '평균 발사각도',
    'BIPs': '인플레이 타구수',
    'HardHits': '강한 타구수'
}

pitcherStatKey1 = ['이닝', 'WHIP', '타석', '피안타', '탈삼진', '볼넷', '홈런',
                   'K%', 'BB%', 'K-BB%', 'HR%', 'K/9', 'BB/9', 'HR/9',
                   'CSW%' ,'헛스윙%', '존컨택%', '체이스%',
                   '피안타율', '피출루율', '피장타율', '피OPS', 'BABIP',
                   '기대피안타율', '기대피출루율', '기대피장타율', '기대피OPS',
                   '존%', '스트%', '땅볼%', '라인%', '뜬공%', '팝업%', '땅/뜬',
                   '강한타구%', '배럴%', '안타성타구%', '투구수']

hitterStatKey1 = ['타석','홈런', '타율', '출루율', '장타율', 'OPS',
                  'BB%', 'K%', 'HR%', 'BABIP',
                  '기대타율', '기대출루율', '기대장타율', '기대OPS',
                  'wOBA', '기대wOBA', '체이스%', '존컨택%', '존스윙%',
                  'PD+EV', 'T-10',
                  '강한타구%', '배럴%','PullAir%', '안타성타구%', '당긴%', '가운데%', '밀어친%',
                   '땅볼%', '라인%', '뜬공%', '팝업%',
                  '최대 타구속도', '평균 타구속도', '평균 발사각도', '인플레이 타구수', '강한 타구수']

hitterStatKey2 = ['타석', '안타', '홈런', '장타', '볼넷', '삼진', '타율', '출루율', '장타율', 'OPS',
                  'BB%', 'K%', 'HR%', 'BABIP', '체이스%', '존컨택%', '존스윙%',
                  '강한타구%', '배럴%', '안타성타구%', '당긴%', '가운데%', '밀어친%',
                  '땅볼%', '라인%', '뜬공%', '팝업%',
                  'wOBA', '기대wOBA', '기대타율', '기대출루율', '기대장타율', '기대OPS',
                  '최대 타구속도', '평균 타구속도', '평균 발사각도', '인플레이 타구수', '강한 타구수']

pitchtype_sortlist = ['Fastball', 'Sinker', 'Slider', 'Cutter', 'Curveball', 'Sweeper',
                      'ChangeUp', 'Splitter', 'Knuckleball', 'Other', 'Undefined']

ptype_sortlist = ['직구(포심)', '직구', '직구(투심)', '직구(싱커)', '직구(원심)', '싱커', '투심',
                  '슬라이더', '커터', '스위퍼', '커브', '너클커브', '슬로커브', '슬러브',
                  '체인지업', '스플리터', '포크볼', '스크류볼', '너클볼', '이퓨스', '미분류']

구종영문_한글로변환 = {
                      'Fastball': '직구',
                      'Sinker': '투심',
                      'Slider': '슬라이더',
                      'Cutter': '커터',
                      'Sweeper': '스위퍼',
                      'Curveball': '커브',
                      'Slurve': '슬러브',
                      'Changeup': '체인지업',
                      'ChangeUp': '체인지업',
                      'Splitter': '포크볼',
                      'Forkball': '포크볼',
                      'Screwball': '스크류볼',
                      'Knuckleball': '너클볼',
                      'Eephus': '이퓨스',
                      'Other': '기타',
                      'Undefined': '미분류'
                  }
구종한글_영문으로변환 = {
    '직구': 'Fastball',
    '투심': 'Sinker',
    '슬라이더': 'Slider',
    '슬라': 'Slider',
    '커터': 'Cutter',
    '스위퍼': 'Sweeper',
    '스위': 'Sweeper',
    '커브': 'Curveball',
    '슬러브': 'Slurve',
    '체인지업': 'ChangeUp',
    '체인': 'ChangeUp',
    '포크': 'Splitter',
    '포크볼': 'Splitter',
    '스플리터': 'Splitter',
    '스플': 'Splitter',
    '너클볼': 'Knuckleball',
    '너클': 'Knuckleball',
    '기타': 'Other',
    '미분류': 'Undefined'
}

구종별_마커 = {
    'Fastball': 'o',
    'Sinker': 'v',
    'Cutter': '<',
    'Cutter-R': '<',
    'Cutter-L': '>',
    'Slider': '<',
    'Slider-R': '<',
    'Slider-L': '>',
    'Curveball': '^',
    'Slurve': '^',
    'Sweeper': '^',
    'ChangeUp': 's',
    'Splitter': 'D',
    'Forkball': 'D',
    'Knuckleball': 'x',
    'Eephus': 'x',
    'Other': 'x',
    'Undefined': 'x'
}


ball_colors = {
    'Fastball': '#ff0000',
    'Sinker': '#ff7800',
    'Cutter': '#00ff00',
    'Slider': '#00aa00',
    'Sweeper': '#4f8f00',
    'Curveball': '#000000',
    'ChangeUp': '#0000ff',
    'Splitter': '#a01ff0',
    'Forkball': '#a01ff0',
    '직구': '#ff0000',
    '포심': '#ff0000',
    '투심': '#ff7800',
    '싱커': '#ff7800',
    '커터': '#00ff00',
    '슬라': '#00aa00',
    '슬라이더': '#00aa00',
    '스위퍼': '#4f8f00',
    '스위': '#4f8f00',
    '커브': '#000000',
    '체인': '#0000ff',
    '체인지업': '#0000ff',
    '스플': '#a01ff0',
    '스플리터': '#a01ff0',
    '포크': '#a01ff0',
    '포크볼': '#a01ff0',
    '스크류볼': '#a01ff0',
    '너클볼': '#a01ff0',
    '이퓨스': '#a01ff0',
    '미분류': '#888888',
    'Eephus': '#a01ff0',
    'Undefined': '#888888',
}

손변환 = {
    'Right': '우',
    'Left': '좌',
    'Side': '우사',
    'LSide': '좌사',
    'Switch': '스위치',
}

구종순서 = ['직구', '투심',
            '슬라', '슬라이더', '커터', '커브', '스위퍼',
            '체인', '체인지업', '포크', '포크볼', '스플', '스플리터',
            '너클', '너클볼', '기타', '미분류', 'Undefined']

손순서 = ['우', '좌', '우사', '좌사', '스위치']


고교야구팀들 = {
    "EPBC(U-18)": ["EUN_U19"],
    "GD챌린저스BC(U18)": ["CHA_CHA15"],
    "HGBC(U-18)": ["HGB_HGB"],
    "TKBC(U19)": ["TKB_TKB"],
    "TNPBA(U-18)": ["TNP_BAS"],
    "강릉고": ["GAN_HIG"],
    "강원고": ["KAN_HIG"],
    "개성고": ["GAE_GAE"],
    "거제BC(U18)": ["GEO_U-1"],
    "경기고": ["GYE_GYE"],
    "경기상업고": ["GYE_TEC"],
    "경기항공고": ["GYE_AVI"],
    "경남고": ["KYU_KYU"],
    "경동고": ["KYU_KYU2"],
    "경민IT고": ["KYU_KYU1"],
    "경북고": ["KYU_HIG"],
    "경주고": ["GYE_HIG"],
    "공주고": ["GON_HIS"],
    "광남고BC(U18)": ["GWA_GWA"],
    "광주동성고": ["GWA_DON"],
    "광주제일고": ["GWA_JAE"],
    "광주진흥고": ["GWA_JIN"],
    "광주BC(U-18)": ["GWA_BC("],
    "군산상업고": ["GUN_COM"],
    "군산상일고": ["GUN_SAN"],
    "글로벌선진학교": ["GSJHS"],
    "금남고": ["GEU_HIG"],
    "김해고": ["GIM_HIS"],
    "나주광남고": ["NAN_GWA"],
    "남양주금곡BC(U-19)": ["NAM_GEU"],
    "남양주GK(U18)": ["NAM_GEU"],
    "달서구BC야구단(U-18)": ["DAL_BC("],
    "대구고": ["DAE_HIG"],
    "대구북구SC(U-18)": ["DAE_BUK"],
    "대구상원고": ["DAE_SAN"],
    "대전고": ["DAE_DAE"],
    "대전제일고": ["DAE_JEI"],
    "덕수고": ["DEO_DEO"],
    "덕적고": ["DEO_DEO1"],
    "도개고": ["DOG_HIG"],
    "동산고": ["DON_DON"],
    "라온고": ["RAO_HIS"],
    "마산고": ["MAS_MAS"],
    "마산용마고": ["MAS_YON"],
    "물금고": ["MUL_HIG"],
    "배명고": ["BAE_HIG"],
    "배재고": ["BAE_HIG1"],
    "백송고": ["BAC_HIG"],
    "부경고": ["BUG_HIG"],
    "부산고": ["BUS_HIG"],
    "부산공업고": ["BUS_TEC"],
    "부산정보고SBC": ["BUS_INF"],
    "부천고": ["BUC_HIG"],
    "북일고": ["BUG_HIG1"],
    "분당BC(U18)": ["BUN_BUN"],
    "비봉고": ["BIB_HIG"],
    "상동고": ["SAN_HIG"],
    "상우고": ["SAN_WOO"],
    "서울고": ["KHS_SEO"],
    "서울동산고": ["SEO_DON"],
    "서울디자인고": ["SEO_DES"],
    "서울자동차고": ["SEO_CAR"],
    "서울컨벤션고": ["KHSSC"],
    "서울HK야구단(U-18)": ["SEO_SEO"],
    "선린인터넷고": ["KHSSR"],
    "설악고": ["KHS_SRK"],
    "성남고": ["SEO_N"],
    "성지고": ["SEO_J"],
    "세광고": ["KHS_SEK"],
    "세원고": ["SEW_HIG"],
    "소래고": ["SOR_H"],
    "순천효천고": ["HYO_HYO"],
    "신일고": ["KHS_SHI"],
    "신흥고": ["SHI_H"],
    "안산공업고": ["ANS_TEC"],
    "야로고BC": ["YAR_B"],
    "야탑고": ["KHS_YAT"],
    "여주IDBC": ["YEO_IDB"],
    "예일메디텍고": ["YEI_MEY"],
    "온양BC(U18)": ["ONY_ONY"],
    "용인시야구단(U-18)": ["YON_BC("],
    "우성베이스볼AC": ["WOO_WOO"],
    "우신고": ["WSHS"],
    "울산공고BC": ["KHS_ULS"],
    "원주고": ["KHS_WON"],
    "유신고": ["YSHS"],
    "율곡고": ["YG_HS"],
    "의성고": ["UIS_UIS"],
    "의왕BC(U18)": ["UIW_BC("],
    "인상고": ["INS_INS"],
    "인창고": ["INC_HIG"],
    "인천고": ["KHSIN"],
    "장안고": ["JAN_JAN"],
    "장충고": ["JAN_JAN1"],
    "전주고": ["JEO_HIG"],
    "제물포고": ["JEM_HIG"],
    "제주고": ["JEJ_JEJ"],
    "중앙고": ["JOO_HIG"],
    "진영고": ["JIN_HIG"],
    "창원공고야구단": ["CHA_TEC"],
    "천안CS": ["CHE_CHE1"],
    "천안CSBC(U-18)": ["CHE_CHE1"],
    "청담고": ["CHU_CHU"],
    "청원고": ["CHE_CHE2"],
    "청주고": ["CHU_HIG"],
    "충암고": ["CHU_CHU1"],
    "충훈고": ["CHO_HIG"],
    "포항제철고": ["POH_JAE"],
    "한광BC(U-18)": ["HAN_BC("],
    "한국마사BC(U18)": ["KOR_MAS"],
    "한국K-POP고": ["KOR_K-P"],
    "화성동탄B(U-18)": ["DON_BC("],
    "화순고": ["HWA_HIG"],
    "휘문고": ["KHSWM"]
};


투수컬럼명변환 = {
    'year': '연도',
    'level': '레벨',
    'IP': '이닝',
    'PA': '타자',
    'hit': '피안타',
    'strikeout': '탈삼진',
    'walk': '볼넷',
    'homerun': '홈런',
    'k_rate': 'K%',
    'bb_rate': 'BB%',
    'k_minus_bb_rate': 'K-BB%',
    'hr_rate': 'HR%',
    'k_per_9': 'K/9',
    'bb_per_9': 'BB/9',
    'hr_per_9': 'HR/9',
    'BA': '피안타율',
    'OBP': '피출루율',
    'SLG': '피장타율',
    'OPS': '피OPS',
    'BABIP': 'BABIP',
    'xBA': '기대피안타율',
    'xOBP': '기대피출루율',
    'xSLG': '기대피장타율',
    'xOPS': '기대피OPS',
    'zone_rate': '존%',
    'strike_rate': '스트%',
    'csw_rate': 'CSW%',
    'whiff_rate': '헛스윙%',
    'zcon_rate': '존컨택%',
    'chase_rate': '체이스%',
    'gb_rate': '땅볼%',
    'ld_rate': '라인%',
    'fb_rate': '뜬공%',
    'pu_rate': '팝업%',
    'gb_per_fb': '땅/뜬',
    'hardhit_rate': '강한타구%',
    'barrel_rate': '배럴%',
    'flareburner_rate': '안타성타구%',
    'pitches': '투구수',
}

타자컬럼명변환 = {
    'year': '연도',
    'level': '레벨',
    'PA': '타석',
    'AB': '타수',
    'homerun': '홈런',
    'BA': '타율',
    'OBP': '출루율',
    'SLG': '장타율',
    'OPS': 'OPS',
    'xBA': '기대타율',
    'xOBP': '기대출루율',
    'xSLG': '기대장타율',
    'xOPS': '기대OPS',
    'BABIP': 'BABIP',
    'wOBA': 'wOBA',
    'xwOBA': '기대wOBA',
    'bb_rate': 'BB%',
    'k_rate': 'K%',
    'hr_rate': 'HR%',
    'hardhit_rate': '강한타구%',
    'barrel_rate': '배럴%',
    'flareburner_rate': '안타성타구%',
    'zswing_rate': '존스윙%',
    'zcon_rate': '존컨택%',
    'chase_rate': '체이스%',
    'swing_rate': '스윙%',
    'ocon_rate': '아웃컨%',
    'con_rate': '컨택%',
    'gb_rate': '땅볼%',
    'ld_rate': '라인%',
    'fb_rate': '뜬공%',
    'pu_rate': '팝업%',
    'pull_rate': '당긴%',
    'center_rate': '가운데%',
    'oppo_rate': '밀어친%',
    'max_ev': '최대 타구속도',
    'mean_ev': '평균 타구속도',
    'mean_la': '평균 발사각도',
    'BIPs': '인플레이 타구수',
    'pullair_rate': 'PullAir%',
    'hardhits': '강한 타구수',
    't10_ev': 'T-10',
    'pd_plus_ev': 'PD+EV',
}



투수컬럼포맷설정 = {
     "이닝": st.column_config.NumberColumn(format='%.1f'),
     "WHIP": st.column_config.NumberColumn(format='%.2f'),
     "K%": st.column_config.NumberColumn(format='%.1f'),
     "BB%": st.column_config.NumberColumn(format='%.1f'),
     "HR%": st.column_config.NumberColumn(format='%.1f'),
     "K-BB%": st.column_config.NumberColumn(format='%.1f'),
     "K/9": st.column_config.NumberColumn(format='%.1f'),
     "BB/9": st.column_config.NumberColumn(format='%.1f'),
     "HR/9": st.column_config.NumberColumn(format='%.1f'),
     "피안타율": st.column_config.NumberColumn(format='%.3f'),
     "피출루율": st.column_config.NumberColumn(format='%.3f'),
     "피장타율": st.column_config.NumberColumn(format='%.3f'),
     "피OPS": st.column_config.NumberColumn(format='%.3f'),
     "BABIP": st.column_config.NumberColumn(format='%.3f', help="인플레이 타구의 타율; (안타-홈런)/(타수+희플-삼진-홈런)"),
     "기대피안타율": st.column_config.NumberColumn(format='%.3f', help='인플레이 타구의 타구속도&발사각에 근거해 예상된 타율'),
     "기대피출루율": st.column_config.NumberColumn(format='%.3f', help='인플레이 타구의 타구속도&발사각에 근거해 예상된 출루율'),
     "기대피장타율": st.column_config.NumberColumn(format='%.3f', help='인플레이 타구의 타구속도&발사각에 근거해 예상된 장타율'),
     "기대피OPS": st.column_config.NumberColumn(format='%.3f', help='인플레이 타구의 타구속도&발사각에 근거해 예상된 OPS'),
     "존%": st.column_config.NumberColumn(format='%.1f'),
     "스트%": st.column_config.NumberColumn(format='%.1f'),
     "땅볼%": st.column_config.NumberColumn(format='%.1f'),
     "라인%": st.column_config.NumberColumn(format='%.1f'),
     "뜬공%": st.column_config.NumberColumn(format='%.1f'),
     "팝업%": st.column_config.NumberColumn(format='%.1f'),
     "땅/뜬": st.column_config.NumberColumn(format='%.2f'),
     "강한타구%": st.column_config.NumberColumn(format='%.1f', help='인플레이 타구 중 타구속도 153km/h 이상인 강한 타구의 비율'),
     "배럴%": st.column_config.NumberColumn(format='%.1f', help='배럴타구 비율; 배럴타구는 타구속도&발사각 기준 기대타율 5할 이상, 기대장타율 1.500 이상인 타구'),
     "안타성타구%": st.column_config.NumberColumn(format='%.1f', help='배럴은 아니지만 기대타율 5할 이상인 타구; 외야 앞에 떨어지는 라인드라이브/텍사스 안타, 강하지만 각도가 낮은 땅볼/라이너 타구 등이 해당함'),
     "CSW%": st.column_config.NumberColumn(format='%.1f', help='전체 투구 중 헛스윙과 루킹스트라이크 비율'),
     "헛스윙%": st.column_config.NumberColumn(format='%.1f', help='스윙이 나왔을 때 헛스윙이 된 비율'),
     "존컨택%": st.column_config.NumberColumn(format='%.1f', help='S존 안에 투구했을 때 컨택된 비율'),
     "체이스%": st.column_config.NumberColumn(format='%.1f', help='존 밖에 투구했을 때 스윙이 끌려나온 비율'),
}
타자컬럼포맷설정 = {
     "K%": st.column_config.NumberColumn(format='%.1f'),
     "BB%": st.column_config.NumberColumn(format='%.1f'),
     "HR%": st.column_config.NumberColumn(format='%.1f'),
     "타율": st.column_config.NumberColumn(format='%.3f'),
     "출루율": st.column_config.NumberColumn(format='%.3f'),
     "장타율": st.column_config.NumberColumn(format='%.3f'),
     "OPS": st.column_config.NumberColumn(format='%.3f'),
     "BABIP": st.column_config.NumberColumn(format='%.3f', help="인플레이 타구의 타율; (안타-홈런)/(타수+희플-삼진-홈런)"),
     "기대타율": st.column_config.NumberColumn(format='%.3f', help='인플레이 타구의 타구속도&발사각에 근거해 예상된 타율'),
     "기대출루율": st.column_config.NumberColumn(format='%.3f', help='인플레이 타구의 타구속도&발사각에 근거해 예상된 출루율'),
     "기대장타율": st.column_config.NumberColumn(format='%.3f', help='인플레이 타구의 타구속도&발사각에 근거해 예상된 장타율'),
     "기대OPS": st.column_config.NumberColumn(format='%.3f', help='인플레이 타구의 타구속도&발사각에 근거해 예상된 OPS'),
     "wOBA": st.column_config.NumberColumn(format='%.3f', help='안타/볼넷/사구 등 각 결과에 가중치를 부여, 계산한 종합 타격 생산성지표'),
     "기대wOBA": st.column_config.NumberColumn(format='%.3f', help='인플레이 타구의 타구속도&발사각에 근거해 예상된 wOBA'),
     "땅볼%": st.column_config.NumberColumn(format='%.1f'),
     "라인%": st.column_config.NumberColumn(format='%.1f'),
     "뜬공%": st.column_config.NumberColumn(format='%.1f'),
     "팝업%": st.column_config.NumberColumn(format='%.1f'),
     "강한타구%": st.column_config.NumberColumn(format='%.1f', help='인플레이 타구 중 타구속도 153km/h 이상인 강한 타구의 비율'),
     "배럴%": st.column_config.NumberColumn(format='%.1f', help='배럴타구 비율; 배럴타구는 타구속도&발사각 기준 기대타율 5할 이상, 기대장타율 1.500 이상인 타구'),
     "안타성타구%": st.column_config.NumberColumn(format='%.1f', help='배럴은 아니지만 기대타율 5할 이상인 타구; 외야 앞에 떨어지는 라인드라이브/텍사스 안타, 강하지만 각도가 낮은 땅볼/라이너 타구 등이 해당함'),
     "존스윙%": st.column_config.NumberColumn(format='%.1f', help='S존 안에 들어온 공에 스윙한 비율'),
     "존컨택%": st.column_config.NumberColumn(format='%.1f', help='S존 안 공에 스윙했을 때 컨택트에 성공한 비율'),
     "체이스%": st.column_config.NumberColumn(format='%.1f', help='S존 바깥의 공에 스윙이 나간 비율'),
     "스윙%": st.column_config.NumberColumn(format='%.1f', help='전체 투구 중 스윙이 나간 비율'),
     "컨택%": st.column_config.NumberColumn(format='%.1f', help='스윙했을 때 컨택트에 성공한 비율'),
     "아웃컨%": st.column_config.NumberColumn(format='%.1f', help='S존 바깥의 공에 스윙했을 때 컨택트에 성공한 비율'),
     "PullAir%": st.column_config.NumberColumn(format='%.1f', help='인플레이 타구 중, 당겨서 라이너/뜬공이 된 타구의 비율; PullAir는 방향+상하각도 분류 중 기대생산성이 가장 높은 유형의 타구임'),
     "당긴%": st.column_config.NumberColumn(format='%.1f', help='인플레이 타구 중, 당겨친 타구의 비율'),
     "가운데%": st.column_config.NumberColumn(format='%.1f', help='인플레이 타구 중, 가운데 방향으로 보낸 타구의 비율'),
     "밀어친%": st.column_config.NumberColumn(format='%.1f', help='인플레이 타구 중, 밀어친 타구의 비율'),
     "PD+EV": st.column_config.NumberColumn(format='%.1f', help='(T-10)x2 + (존컨택-체이스x2)'),
     "T-10": st.column_config.NumberColumn(format='%.1f', help='선수 개인의 인플레이 타구속도 중 기준 상위 10%에 해당하는 값'),
     "최대 타구속도": st.column_config.NumberColumn(format='%.1f', help='선수 개인의 인플레이 타구속도 최대값'),
     "평균 타구속도": st.column_config.NumberColumn(format='%.1f', help='선수 개인의 인플레이 타구속도 평균값'),
     "평균 발사각도": st.column_config.NumberColumn(format='%.1f', help='선수 개인의 인플레이 타구 발사각도 평균값'),
 }

타자리더보드_표시컬럼 = [
    '나이',
    '타석', '홈런', '타율', '출루율', '장타율', 'OPS',
    'BB%', 'K%', 'HR%', 'BABIP',
    '기대타율', '기대출루율', '기대장타율', '기대OPS',
    'wOBA', '기대wOBA', '체이스%', '존컨택%', '존스윙%', '스윙%', '컨택%',
    'PD+EV', 'T-10',
    '강한타구%', '배럴%','PullAir%', '안타성타구%',
    '당긴%', '가운데%', '밀어친%',
    '땅볼%', '라인%', '뜬공%', '팝업%',
    '최대 타구속도', '평균 타구속도', '평균 발사각도',
    '인플레이 타구수', '강한 타구수',
    # 타수, 아웃컨%
]

투수리더보드_표시컬럼 = [
    '나이',
    '이닝', 'WHIP', '타자', '피안타', '탈삼진', '볼넷', '홈런',
    'K%', 'BB%', 'K-BB%', 'HR%', 'K/9', 'BB/9', 'HR/9',
    'CSW%' ,'헛스윙%', '존컨택%', '체이스%',
    '스트%', '존%', 
    '피안타율', '피출루율', '피장타율', '피OPS', 'BABIP',
    '기대피안타율', '기대피출루율', '기대피장타율', '기대피OPS',
    '땅볼%', '라인%', '뜬공%', '팝업%', '땅/뜬',
    '강한타구%', '배럴%', '안타성타구%', '투구수',
]



team_name = {
    'KIA_TIG': 'KIA',
    'MIN_KIA': 'KIA 퓨처스',
    'KT_WIZ': 'KT',
    'MIN_KTW': 'KT 퓨처스',
    'LG_TWI': 'LG',
    'MIN_LGT': 'LG 퓨처스',
    'NC_DIN': 'NC',
    'MIN_NCD': 'NC 퓨처스',
    'SSG_LAN': 'SSG',
    'MIN_SSG': 'SSG 퓨처스',
    'SK_WYV': 'SK',
    'MIN_SKW': 'SK 퓨처스',
    'DOO_BEA': '두산',
    'MIN_DOO': '두산 퓨처스',
    'LOT_GIA': '롯데',
    'MIN_LOT': '롯데 퓨처스',
    'SAM_LIO': '삼성',
    'MIN_SAM': '삼성 퓨처스',
    'KIW_HER': '키움',
    'MIN_KIW': '키움 퓨처스',
    'HAN_EAG': '한화',
    'MIN_HAN': '한화 퓨처스',
    'KBO_AVG': '리그 평균'
}

team_colors = {
    'KIA_TIG': '#ac1f27',
    'MIN_KIA': '#ac1f27',
    'KT_WIZ': '#000000',
    'MIN_KTW': '#000000',
    'LG_TWI': '#808080',
    'MIN_LGT': '#808080',
    'NC_DIN': '#193862',
    'MIN_NCD': '#193862',
    'SSG_LAN': '#ff0000',
    'MIN_SSG': '#ff0000',
    'SK_WYV': '#ff0000',
    'MIN_SKW': '#ff0000',
    'DOO_BEA': '#120e29',
    'MIN_DOO': '#120e29',
    'LOT_GIA': '#0e2c56',
    'MIN_LOT': '#0e2c56',
    'SAM_LIO': '#0065B3',
    'MIN_SAM': '#0065B3',
    'KIW_HER': '#670017',
    'MIN_KIW': '#670017',
    'HAN_EAG': '#ed7d31',
    'MIN_HAN': '#ed7d31',
    'KBO_AVG': '#00cc00'
}

ball_colors = {
    'Fastball': '#ff0000',
    'Sinker': '#ff7800',
    'Cutter': '#00ff00',
    'Slider': '#00aa00',
    'Sweeper': '#4f8f00',
    'Curveball': '#000000',
    'ChangeUp': '#0000ff',
    'Splitter': '#a01ff0',
    'Forkball': '#a01ff0',
}
ball_code = {
    'Fastball': 'FB',
    'Sinker': 'FT',
    'Cutter': 'CT',
    'Slider': 'SL',
    'Sweeper': 'SW',
    'Curveball': 'CB',
    'ChangeUp': 'CH',
    'Splitter': 'SP',
    'Knuckelball': 'KN',
    'Forkball': 'FK',
}

ptype_short = {
    'Fastball': 'FB(4S)',
    'Sinker': 'FB(2S)',
    'Cutter': 'CT',
    'Slider': 'SL',
    'Sweeper': 'SW',
    'Curveball': 'CB',
    'ChangeUp': 'CH',
    'Splitter': 'SP',
    'Knuckelball': 'KN',
    'Forkball': 'FK',
}

p_kor_dict = {
    'Fastball': '직구',
    'Sinker': '투심',
    'Cutter': '커터',
    'Slider': '슬라이더',
    'Sweeper': '스위퍼',
    'Curveball': '커브',
    'ChangeUp': '체인지업',
    'Splitter': '포크볼',
    'Knuckleball': '너클볼',
    'Forkball': '포크볼',
}

p_eng_dict = {
    '직구': 'Fastball',
    '투심': 'Sinker',
    '커터': 'Cutter',
    '슬라': 'Slider',
    '스위': 'Sweeper',
    '커브': 'Curveball',
    '스플': 'Splitter',
    '포크': 'Splitter',
    '체인': 'Changeup',
    '기타': 'Other',
}

type3_colors = {
    'Fastball': 'red',
    'Breaking': 'green',
    'Offspeed': '#a01ff0'
}
type4_colors = {
    'Fastball': 'red',
    'Breaking': 'green',
    'Curveball': '#191970',#'Midnight Blue',
    'Offspeed': '#a01ff0'
}
ptypes = {
    'Fastball': ['Fastball', 'Sinker'],
    'Breaking': ['Cutter', 'Slider', 'Curveball', 'Sweeper'],
    'Offspeed': ['ChangeUp', 'Splitter']
}
ptypes4 = {
    'Fastball': ['Fastball', 'Sinker'],
    'Breaking': ['Cutter', 'Slider', 'Sweeper'],
    'Curveball': ['Curveball'],
    'Offspeed': ['ChangeUp', 'Splitter']
}
ptype_kor = {
    'Fastball': '직구/투심',
    'Breaking': '슬라/커브',
    'Offspeed': '포크/체인'
}
ptype_kor4 = {
    'Fastball': '직구/투심',
    'Breaking': '슬라/커터',
    'Curveball': '커브',
    'Offspeed': '포크/체인'
}

stadiumDict = {
    'Daejeon': '대전',
    'Incheon': '문학',
    'Jamsil': '잠실',
    'NCDinosMajors': '창원',
    'Suwon': '수원',
    'Sajik': '사직',
    'Gocheok': '고척',
    'DaeguPark': '대구'
}

sort_order = list(ball_colors.keys())
coolwarm_trim = ListedColormap(np.vstack((np.zeros((10,4)), cm.coolwarm(np.linspace(0, 1, 256))[10:])))
orange_grey = ListedColormap(np.vstack((np.zeros((10,4)),
                                        cm.Greys(np.linspace(0, 1, 256))[128:10:-1],
                                        cm.Oranges(np.linspace(0, 1, 128)))))
red_layer_color = (0.98, 0.29, 0.32, 1)
yellow_layer_color = (0.98, 0.99, 0.16, 1)
blue_layer_color = (65/255, 105/255, 225/255, 1)

rwb_front = np.linspace(red_layer_color, yellow_layer_color, 85).reshape(85, 4)
rwb_back = np.linspace(np.ones((1, 4)), np.asarray(blue_layer_color), 85).reshape(85, 4)
rwb = ListedColormap(np.vstack((rwb_front, np.ones((86, 4)), rwb_back)))

레벨영어변환 = {
    '1군': 'kbo',
    '퓨처스': 'kbo minors',
    '정규': 'regular',
    '포스트시즌': 'postseason',
    '정규+포시': 'regular and postseason',
    '시범': 'exhibition',
    '전체': None
}
